
"""
Configuration Module
Centralized settings for the NSE stock screening engine.
All API keys loaded from environment variables.
"""

import os
from dotenv import load_dotenv

load_dotenv()

# API KEYS
SUPABASE_URL = os.getenv("SUPABASE_URL", "")
SUPABASE_SERVICE_KEY = os.getenv("SUPABASE_SERVICE_KEY", "")
FINNHUB_API_KEY = os.getenv("FINNHUB_API_KEY", "")
FMP_API_KEY = os.getenv("FMP_API_KEY", "")

# NSE STOCK UNIVERSE
NSE_UNIVERSE = [
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", "HINDUNILVR",
    "ITC", "SBIN", "BHARTIARTL", "KOTAKBANK", "LT", "BAJFINANCE",
    "WIPRO", "HCLTECH", "ASIANPAINT", "MARUTI", "SUNPHARMA", "TITAN",
    "AXISBANK", "NTPC", "ONGC", "POWERGRID", "ULTRACEMCO",
    "M&M", "TATASTEEL", "JSWSTEEL", "TECHM", "INDUSINDBK", "BAJAJFINSV",
    "NESTLEIND", "ADANIPORTS", "TATAMOTORS", "COALINDIA", "IOC",
    "SHREECEM", "GRASIM", "DRREDDY", "BPCL", "DIVISLAB", "BRITANNIA",
    "HINDALCO", "EICHERMOT", "CIPLA", "HEROMOTOCO", "BAJAJ-AUTO",
    "APOLLOHOSP", "SBILIFE", "HDFCLIFE", "TATACONSUM",
    "ADANIENT", "ADANIGREEN", "ADANIPOWER", "ADANITRANS", "AMBUJACEM",
    "AUROPHARMA", "BANDHANBNK", "BERGEPAINT", "BHARATFORG", "BOSCHLTD",
    "CADILAHC", "CANBK", "CHOLAFIN", "COLGATE", "CONCOR",
    "DABUR", "DALBHARAT", "DLF", "ESCORTS", "FEDERALBNK", "GAIL",
    "GODREJCP", "GODREJPROP", "GUJGASLTD", "HAL", "HAVELLS",
    "HDFCAMC", "HINDZINC", "ICICIPRULI", "ICICIGI",
    "IDFCFIRSTB", "IGL", "INDIGO", "INDUSTOWER",
    "IREDA", "IRCTC", "JIOFIN", "KPITTECH", "LICI",
    "LTIM", "LUPIN", "MFSL", "MOTHERSON",
    "MPHASIS", "MRF", "MUTHOOTFIN", "NATIONALUM", "NAUKRI",
    "NYKAA", "OIL", "PAGEIND", "PEL", "PERSISTENT", "PETRONET",
    "PIDILITIND", "PIIND", "PNB", "POLYCAB",
    "PVRINOX", "RBLBANK", "RECLTD", "SAIL", "SBICARD",
    "SIEMENS", "SRTRANSFIN", "SUNDARMFIN", "SUNTV", "SYNGENE",
    "TATACOMM", "TATAELXSI", "TATAPOWER", "TATATECH", "TORNTPHARM",
    "TRENT", "TVSMOTOR", "UBL", "VBL", "VEDL", "VOLTAS",
    "WHIRLPOOL", "YESBANK", "ZOMATO", "ZYDUSLIFE",
    "AARTIIND", "ABB", "ABCAPITAL", "ABFRL", "ACC", "ALKEM",
    "ANGELONE", "APOLLOTYRE", "ASHOKLEY", "ASTRAL", "ATGL",
    "AUBANK", "BAJAJHLDNG", "BALKRISIND",
    "BALRAMCHIN", "BANKBARODA", "BATAINDIA", "BEL", "BEML",
    "BHEL", "BIOCON", "BSE",
    "CDSL", "CESC", "CGPOWER", "CHAMBLFERT",
    "COFORGE", "COLPAL", "COROMANDEL", "CRISIL", "CROMPTON",
    "CUMMINSIND", "DEEPAKNTR",
    "DMART", "DIXON", "EIDPARRY",
    "ENGINERSIN", "EXIDEIND",
    "GLENMARK", "GMRINFRA", "GNFC",
    "GRANULES", "GRAPHITE", "GREAVESCOT", "GSFC",
    "HINDCOPPER", "HUDCO", "IBULHSGFIN",
    "INDHOTEL", "INDIACEM", "INDIAMART",
    "INTELLECT", "IPCALAB",
    "IRB", "IRCON", "JINDALSTEL", "JKCEMENT",
    "JSWENERGY", "JUBLFOOD",
    "JUSTDIAL", "KALPATPOWR", "KARURVYSYA", "KEI",
    "L&TFH", "LAURUSLABS",
    "LINDEINDIA", "LTTS",
    "M&MFIN", "MAHABANK",
    "MANAPPURAM", "MARICO",
    "MAXHEALTH", "MCX", "METROPOLIS",
    "MGL", "MOTHERSUMI",
    "MTARTECH", "NATCOPHARM", "NBCC", "NCC",
    "NHPC", "NIACL",
    "NLCINDIA", "NMDC", "NOCIL",
    "OBEROIRLTY", "OFSS", "OLECTRA",
    "PCBL", "PFIZER", "PGHH", "PHOENIXLTD",
    "PNBHOUSING", "POLICYBZR",
    "PRAJIND", "PRESTIGE", "PRINCEPIPE",
    "RAIN", "RAMCOCEM",
    "RALLIS", "RATNAMANI", "RAYMOND",
    "RCF", "REDINGTON", "RELAXO",
    "RITES",
    "SANOFI", "SHARDACROP", "SHRIRAMFIN",
    "SKFINDIA", "SONACOMS",
    "SRF", "STARCEMENT",
    "SUMICHEM", "SUNDRMFAST",
    "SUPREMEIND", "SUVENPHAR",
    "TATACHEM", "TEJASNET", "THERMAX",
    "TIINDIA", "TIMKEN", "TITAGARH",
    "TORNTPOWER", "TRIDENT",
    "TTKPRESTIG", "TV18BRDCST",
    "UCOBANK", "UJJIVAN", "UJJIVANSFB",
    "UNIONBANK", "UNOMINDA", "UPL",
    "UTIAMC", "VINATIORGA",
    "WELCORP", "WELSPUNLIV",
    "ZEEL", "ZENSARTECH",
]

def get_yfinance_ticker(ticker):
    return ticker + ".NS"

WEIGHTS = {
    "technical": {"rsi_momentum": 15, "macd_signal": 15, "volume_spike": 15, "ma_crossover": 10, "breakout_potential": 10},
    "fundamental": {"pe_relative": 10, "market_cap_score": 5, "volume_ratio": 10},
    "sentiment": {"news_sentiment": 5, "relative_strength": 5},
}

MAX_TOTAL_SCORE = 100
MIN_PRICE = 50.0
MIN_VOLUME = 100000
MIN_MARKET_CAP = 500000000
MIN_AVERAGE_VOLUME = 50000

NSE_MARKET_OPEN = "09:15"
NSE_MARKET_CLOSE = "15:30"
DAILY_RUN_HOUR_IST = 7

LOOKBACK_DAYS = 60
SCREENING_PERIOD = 20
