"""
Database Module
===============
Handles all Supabase interactions for storing and retrieving
daily stock picks and historical data.

Schema Design (for Supabase SQL Editor):
-----------------------------------------

-- Table: daily_picks (one row per day's screening)
CREATE TABLE daily_picks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_date DATE NOT NULL UNIQUE,
    total_stocks_screened INTEGER,
    avg_score DECIMAL(5,2),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: picks (individual stock picks per day)
CREATE TABLE picks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_pick_id BIGINT REFERENCES daily_picks(id) ON DELETE CASCADE,
    rank INTEGER NOT NULL,
    ticker VARCHAR(10) NOT NULL,
    company_name VARCHAR(255),
    current_price DECIMAL(10,2),
    previous_close DECIMAL(10,2),
    change_pct DECIMAL(6,2),
    volume BIGINT,
    avg_volume_90d BIGINT,
    market_cap BIGINT,
    sector VARCHAR(100),
    industry VARCHAR(100),
    pe_ratio DECIMAL(8,2),
    score DECIMAL(5,2),
    rsi DECIMAL(5,2),
    volume_ratio_20d DECIMAL(5,2),
    entry_suggestion TEXT,
    stop_loss DECIMAL(10,2),
    target_price DECIMAL(10,2),
    bullish_reasons TEXT[],  -- Array of reasons
    risk_level VARCHAR(20),
    technical_score DECIMAL(5,2),
    fundamental_score DECIMAL(5,2),
    sentiment_score DECIMAL(5,2),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast queries
CREATE INDEX idx_picks_date ON picks(daily_pick_id);
CREATE INDEX idx_picks_ticker ON picks(ticker);
CREATE INDEX idx_picks_score ON picks(score DESC);

-- Table: stock_history (historical price tracking for picks)
CREATE TABLE stock_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker VARCHAR(10) NOT NULL,
    date DATE NOT NULL,
    open_price DECIMAL(10,2),
    high_price DECIMAL(10,2),
    low_price DECIMAL(10,2),
    close_price DECIMAL(10,2),
    volume BIGINT,
    rsi_14 DECIMAL(5,2),
    macd_line DECIMAL(8,4),
    macd_signal DECIMAL(8,4),
    UNIQUE(ticker, date)
);
"""

import os
import logging
import math
from datetime import datetime, date
from typing import List, Dict, Optional
from supabase import create_client, Client

from src.config import SUPABASE_URL, SUPABASE_SERVICE_KEY

logger = logging.getLogger(__name__)


def _safe_db_float(value, default=0.0):
    """Ensure a value is safe for database insertion (no NaN/inf)."""
    try:
        result = float(value)
        if math.isnan(result) or math.isinf(result):
            return default
        return result
    except (TypeError, ValueError):
        return default


class PickDatabase:
    """Manages all database operations for stock picks."""
    
    def __init__(self):
        if not SUPABASE_URL or not SUPABASE_SERVICE_KEY:
            logger.warning("Supabase credentials not configured. Running in memory-only mode.")
            self.client = None
        else:
            self.client: Client = create_client(SUPABASE_URL, SUPABASE_SERVICE_KEY)
    
    def save_daily_picks(self, picks: List[Dict], today: date = None) -> bool:
        """
        Save a day's top 10 picks to the database.
        
        Args:
            picks: List of pick dictionaries (from screener.get_top_10_picks)
            today: Date for this run. Defaults to today.
        
        Returns:
            True if successful, False otherwise.
        """
        if self.client is None:
            logger.info("In-memory mode: printing picks instead of saving.")
            self._print_picks(picks)
            return True
        
        try:
            today = today or date.today()
            
            # Upsert daily_picks record
            daily_data = {
                "run_date": today.isoformat(),
                "total_stocks_screened": len(picks),
                "avg_score": round(sum(p["score"] for p in picks) / len(picks), 2) if picks else 0,
            }
            
            # Check if we already have today's record
            existing = self.client.table("daily_picks") \
                .select("*") \
                .eq("run_date", today.isoformat()) \
                .execute()
            
            if existing.data:
                daily_pick_id = existing.data[0]["id"]
            else:
                result = self.client.table("daily_picks") \
                    .insert(daily_data) \
                    .execute()
                daily_pick_id = result.data[0]["id"]
            
            # Delete old picks for this day (for idempotency)
            self.client.table("picks") \
                .delete() \
                .eq("daily_pick_id", daily_pick_id) \
                .execute()
            
            # Insert each pick
            for rank, pick in enumerate(picks, 1):
                rationale = pick.get("rationale", {})
                # Deduplicate: read from rationale OR pick (for DB reads)
                entry_sugg = rationale.get("entry_suggestion") or pick.get("entry_suggestion", "")
                stop_loss = _safe_db_float(rationale.get("suggested_stop_loss") or pick.get("stop_loss", 0))
                target_price = _safe_db_float(rationale.get("suggested_target") or pick.get("target_price", 0))
                bullish_reasons = rationale.get("bullish_reasons") or pick.get("bullish_reasons", [])
                risk_level = rationale.get("risk_level") or pick.get("risk_level", "Moderate")
                
                pick_data = {
                    "daily_pick_id": daily_pick_id,
                    "rank": rank,
                    "ticker": pick.get("ticker", ""),
                    "company_name": pick.get("company_name", "")[:255],
                    "current_price": _safe_db_float(pick.get("current_price", 0)),
                    "previous_close": _safe_db_float(pick.get("previous_close", 0)),
                    "change_pct": _safe_db_float(pick.get("change_pct", 0)),
                    "volume": int(_safe_db_float(pick.get("volume", 0))),
                    "avg_volume_90d": int(_safe_db_float(pick.get("avg_volume_90d", 0))),
                    "market_cap": int(_safe_db_float(pick.get("market_cap", 0))),
                    "sector": pick.get("sector", "N/A")[:100],
                    "industry": pick.get("industry", "N/A")[:100],
                    "pe_ratio": _safe_db_float(pick.get("pe_ratio", 0)),
                    "score": _safe_db_float(pick.get("score", 0)),
                    "rsi": _safe_db_float(pick.get("rsi", 50), 50.0),
                    "volume_ratio_20d": _safe_db_float(pick.get("volume_ratio_20d", 1.0), 1.0),
                    "entry_suggestion": entry_sugg,
                    "stop_loss": stop_loss,
                    "target_price": target_price,
                    "bullish_reasons": bullish_reasons if isinstance(bullish_reasons, list) else [],
                    "risk_level": risk_level[:20],
                    "technical_score": _safe_db_float(pick.get("breakdown", {}).get("technical", {}).get("total_technical", 0)),
                    "fundamental_score": _safe_db_float(pick.get("breakdown", {}).get("fundamental", {}).get("total_fundamental", 0)),
                    "sentiment_score": _safe_db_float(pick.get("sentiment", 0.5) * 10),
                }
                
                self.client.table("picks") \
                    .insert(pick_data) \
                    .execute()
            
            logger.info(f"Saved {len(picks)} picks for {today}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to save picks to database: {e}")
            return False
    
    def get_daily_picks(self, target_date: date = None) -> List[Dict]:
        """
        Retrieve picks for a given date.
        
        Args:
            target_date: Date to retrieve. Defaults to today.
            
        Returns:
            List of pick dictionaries.
        """
        target_date = target_date or date.today()
        
        if self.client is None:
            logger.warning("Database not configured. Cannot retrieve picks.")
            return []
        
        try:
            # Find the daily_picks record
            daily = self.client.table("daily_picks") \
                .select("*") \
                .eq("run_date", target_date.isoformat()) \
                .execute()
            
            if not daily.data:
                logger.info(f"No picks found for {target_date}")
                return []
            
            daily_pick_id = daily.data[0]["id"]
            
            # Get all picks for this day, ordered by rank
            result = self.client.table("picks") \
                .select("*") \
                .eq("daily_pick_id", daily_pick_id) \
                .order("rank") \
                .execute()
            
            return result.data
            
        except Exception as e:
            logger.error(f"Failed to retrieve picks: {e}")
            return []
    
    def get_pick_history(self, ticker: str, days: int = 30) -> List[Dict]:
        """
        Get the history of a stock's appearance in daily picks.
        
        Args:
            ticker: Stock ticker symbol.
            days: Lookback period.
            
        Returns:
            List of historical pick records.
        """
        if self.client is None:
            return []
        
        try:
            result = self.client.table("picks") \
                .select("*, daily_picks!inner(run_date)") \
                .eq("ticker", ticker) \
                .order("daily_picks.run_date", desc=True) \
                .limit(days) \
                .execute()
            return result.data
        except Exception as e:
            logger.error(f"Failed to get history for {ticker}: {e}")
            return []
    
    def get_performance_stats(self, days: int = 30) -> Dict:
        """
        Calculate performance statistics for recent picks.
        This is a simplified version - real tracking requires
        comparing pick prices to subsequent close prices.
        """
        if self.client is None:
            return {"error": "Database not configured"}
        
        try:
            # Get recent daily runs
            recent = self.client.table("daily_picks") \
                .select("*") \
                .order("run_date", desc=True) \
                .limit(days) \
                .execute()
            
            if not recent.data:
                return {"error": "No data available"}
            
            return {
                "total_days": len(recent.data),
                "recent_runs": recent.data,
            }
        except Exception as e:
            logger.error(f"Failed to get stats: {e}")
            return {"error": str(e)}
    
    def _print_picks(self, picks: List[Dict]):
        """Fallback: print picks to console if no DB."""
        print(f"\n{'='*70}")
        print(f"📈 DAILY TOP 10 PICKS - {date.today()}")
        print(f"{'='*70}")
        for i, pick in enumerate(picks, 1):
            rationale = pick.get("rationale", {})
            print(f"\n#{i} {pick['ticker']} (${pick['current_price']}) - Score: {pick['score']:.1f}")
            print(f"   {pick.get('company_name', 'N/A')}")
            print(f"   Sector: {rationale.get('sector', 'N/A')} | Mkt Cap: {rationale.get('market_cap_formatted', 'N/A')}")
            print(f"   Entry: {rationale.get('entry_suggestion', 'N/A')} | Stop: ${rationale.get('suggested_stop_loss', 0)} | Target: ${rationale.get('suggested_target', 0)}")
            for reason in rationale.get("bullish_reasons", []):
                print(f"   ✓ {reason}")
            print(f"   Score Breakdown: {rationale.get('score_breakdown', 'N/A')}")


if __name__ == "__main__":
    # Test database connection
    db = PickDatabase()
    print("Testing database connection...")
    
    if db.client:
        result = db.client.table("daily_picks").select("count", count="exact").execute()
        print(f"Connected! Existing records: {result.count}")
    else:
        print("No database configured. Running in memory mode.")
