"""
Daily Pipeline Runner
=====================
Orchestrates the full daily workflow:
1. Fetch news/sentiment for top candidates
2. Run market screener
3. Score and rank stocks
4. Enrich with sentiment data
5. Save to database
6. Generate report

This script is designed to run as a GitHub Actions cron job
or a scheduled task on a free platform.
"""

import os
import sys
import json
import logging
import time
import math
from datetime import datetime, date, timedelta
from typing import List, Dict, Optional
import requests

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.screener import MarketScreener
from src.database import PickDatabase
from src.config import FINNHUB_API_KEY, FMP_API_KEY, NSE_UNIVERSE

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler("pipeline.log"),
    ]
)
logger = logging.getLogger(__name__)


class NewsSentimentAnalyzer:
    """
    Fetches news sentiment using Finnhub free API.
    Free tier: 300 API calls/day - we use ~10-20 for top candidates.
    """
    
    def __init__(self, api_key: str = FINNHUB_API_KEY):
        self.api_key = api_key
        if not api_key:
            logger.warning("No Finnhub API key. Sentiment analysis disabled.")
    
    def get_sentiment(self, ticker: str) -> float:
        """
        Get news sentiment score for a ticker.
        Returns value from 0 (negative) to 1 (positive), default 0.5.
        """
        if not self.api_key:
            return 0.5
        
        try:
            url = f"https://finnhub.io/api/v1/news-sentiment"
            params = {
                "symbol": ticker,
                "token": self.api_key,
                "from": (date.today() - timedelta(days=7)).isoformat(),
                "to": date.today().isoformat(),
            }
            
            resp = requests.get(url, params=params, timeout=10)
            if resp.status_code == 200:
                data = resp.json()
                sentiment = data.get("sentimentScore", 0.5)
                buzz = data.get("buzz", {})
                company_news_count = buzz.get("companyNewsCount", 0)
                
                # Boost score if there's recent news coverage
                if company_news_count > 0:
                    # Sentiment is between 0-1, we add a small buzz boost
                    sentiment = min(1.0, sentiment + (company_news_count * 0.02))
                
                return max(0.0, min(1.0, sentiment))
            else:
                logger.debug(f"Finnhub sentiment failed for {ticker}: {resp.status_code}")
                return 0.5
                
        except Exception as e:
            logger.debug(f"Error fetching sentiment for {ticker}: {e}")
            return 0.5
    
    def get_batch_sentiment(self, tickers: List[str]) -> Dict[str, float]:
        """
        Get sentiment for multiple tickers.
        We limit to top 15-20 to conserve API calls.
        """
        sentiments = {}
        for i, ticker in enumerate(tickers):
            sentiments[ticker] = self.get_sentiment(ticker)
            if i > 0 and i % 5 == 0:
                time.sleep(1)  # Rate limiting
        return sentiments


class ReportGenerator:
    """Generates summary reports from picks data."""
    
    @staticmethod
    def generate_markdown_report(picks: List[Dict]) -> str:
        """Generate a markdown summary of the day's picks."""
        today = date.today().strftime("%Y-%m-%d")
        
        md = f"""# 📈 Daily Top 10 Stock Picks — {today}

> Generated by automated market screening engine.
> *Disclaimer: This is for educational/research purposes only. Not financial advice.*

---

## Summary

| # | Ticker | Price | Score | RSI | Entry Suggestion |
|---|--------|-------|-------|-----|-----------------|
"""
        for i, pick in enumerate(picks, 1):
            r = pick.get("rationale", {})
            md += f"| {i} | {pick['ticker']} | ${pick['current_price']} | {pick['score']:.1f} | {pick.get('rsi', 50):.1f} | {r.get('entry_suggestion', 'N/A')} |\n"
        
        md += "\n## Detailed Analysis\n\n"
        for pick in picks:
            r = pick.get("rationale", {})
            md += f"### {pick['ticker']} ({pick.get('company_name', 'N/A')})\n"
            md += f"- **Price:** ${pick['current_price']} | **Score:** {pick['score']:.1f}/100\n"
            md += f"- **Sector:** {r.get('sector', 'N/A')} | **Market Cap:** {r.get('market_cap_formatted', 'N/A')}\n"
            md += f"- **P/E Ratio:** {pick.get('pe_ratio', 'N/A')}\n"
            md += f"- **Volume Ratio (20d avg):** {pick.get('volume_ratio_20d', 1):.2f}x\n"
            md += f"- **Entry:** {r.get('entry_suggestion', 'N/A')}\n"
            md += f"- **Stop Loss:** ${r.get('suggested_stop_loss', 0)} | **Target:** ${r.get('suggested_target', 0)}\n"
            md += f"- **Risk Level:** {r.get('risk_level', 'Moderate')}\n"
            md += "- **Bullish Indicators:**\n"
            for reason in r.get("bullish_reasons", []):
                md += f"  - ✅ {reason}\n"
            md += f"- **Score Breakdown:** {r.get('score_breakdown', 'N/A')}\n"
            md += "\n"
        
        return md
    
    @staticmethod
    def generate_json_report(picks: List[Dict]) -> str:
        """Generate a JSON-serializable report with NaN/inf safety."""
        report = {
            "date": date.today().isoformat(),
            "generated_at": datetime.now().isoformat(),
            "total_analyzed": "300+ NSE stocks",
            "top_picks": []
        }
        
        for i, pick in enumerate(picks, 1):
            r = pick.get("rationale", {})
            def sf(v, d=0):
                try:
                    f = float(v)
                    if math.isnan(f) or math.isinf(f):
                        return d
                    return f
                except (TypeError, ValueError):
                    return d

            pick_entry = {
                "rank": i,
                "ticker": pick.get("ticker", ""),
                "company_name": pick.get("company_name", ""),
                "current_price": sf(pick.get("current_price", 0)),
                "previous_close": sf(pick.get("previous_close", 0)),
                "change_pct": sf(pick.get("change_pct", 0)),
                "volume": int(sf(pick.get("volume", 0))),
                "avg_volume_90d": int(sf(pick.get("avg_volume_90d", 0))),
                "market_cap": int(sf(pick.get("market_cap", 0))),
                "sector": r.get("sector") or pick.get("sector", "N/A"),
                "industry": pick.get("industry", "N/A"),
                "pe_ratio": sf(pick.get("pe_ratio", 0)),
                "score": sf(pick.get("score", 0)),
                "rsi": sf(pick.get("rsi", 50), 50),
                "volume_ratio_20d": sf(pick.get("volume_ratio_20d", 1.0), 1.0),
                # Flat columns for DB-like access from dashboard
                "entry_suggestion": r.get("entry_suggestion", ""),
                "stop_loss": sf(r.get("suggested_stop_loss", 0)),
                "target_price": sf(r.get("suggested_target", 0)),
                "risk_level": r.get("risk_level", "Moderate"),
                "bullish_reasons": r.get("bullish_reasons", []),
                # Nested rationale for dashboard reports
                "rationale": {
                    "entry_suggestion": r.get("entry_suggestion", ""),
                    "entry_price": sf(r.get("entry_price", pick.get("current_price", 0))),
                    "suggested_stop_loss": sf(r.get("suggested_stop_loss", 0)),
                    "suggested_target": sf(r.get("suggested_target", 0)),
                    "stop_loss": sf(r.get("stop_loss", r.get("suggested_stop_loss", 0))),
                    "target_price": sf(r.get("target_price", r.get("suggested_target", 0))),
                    "risk_level": r.get("risk_level", "Moderate"),
                    "bullish_reasons": r.get("bullish_reasons", []),
                    "sector": r.get("sector") or pick.get("sector", "N/A"),
                    "market_cap_formatted": r.get("market_cap_formatted", ""),
                    "market_cap_raw": sf(r.get("market_cap_raw", 0)),
                    "score_breakdown": r.get("score_breakdown", ""),
                }
            }
            report["top_picks"].append(pick_entry)

        return json.dumps(report, indent=2)


def run_daily_pipeline():
    """
    Main function that orchestrates the daily pipeline.
    
    Steps:
    1. Initialize all components
    2. Run market screening
    3. Fetch sentiment for top candidates
    4. Compute final scores
    5. Select top 10
    6. Save to database
    7. Generate reports
    """
    start_time = datetime.now()
    logger.info("🚀 Starting daily stock screening pipeline...")
    
    # Step 1: Initialize
    screener = MarketScreener()
    db = PickDatabase()
    sentiment_analyzer = NewsSentimentAnalyzer()
    
    # Step 2: Screen the market
    logger.info("Step 1/4: Screening market universe...")
    candidates = screener.screen_market()
    logger.info(f"Found {len(candidates)} qualifying stocks")
    
    if not candidates:
        logger.error("No qualifying stocks found! Check filters.")
        return False
    
    # Step 3: Get sentiment for top candidates
    logger.info("Step 2/4: Fetching news sentiment...")
    top_candidates = [c["ticker"] for c in candidates[:15]]
    sentiments = sentiment_analyzer.get_batch_sentiment(top_candidates)
    logger.info(f"Sentiment fetched for {len(sentiments)} stocks")
    
    # Step 4: Generate final top 10
    logger.info("Step 3/4: Computing final rankings...")
    top_10 = screener.get_top_10_picks(news_sentiment=sentiments)
    
    # Step 5: Save to database
    logger.info("Step 4/4: Saving to database...")
    save_success = db.save_daily_picks(top_10)
    
    # Step 6: Generate reports
    md_report = ReportGenerator.generate_markdown_report(top_10)
    json_report = ReportGenerator.generate_json_report(top_10)
    
    # Save reports to files
    reports_dir = "reports"
    os.makedirs(reports_dir, exist_ok=True)
    
    today_str = date.today().isoformat()
    with open(f"{reports_dir}/picks_{today_str}.md", "w") as f:
        f.write(md_report)
    with open(f"{reports_dir}/picks_{today_str}.json", "w") as f:
        f.write(json_report)
    
    elapsed = (datetime.now() - start_time).total_seconds()
    logger.info(f"✅ Pipeline complete! ({elapsed:.1f}s)")
    logger.info(f"Reports saved to {reports_dir}/")
    
    return True


def run_daily_at_open():
    """
    Wrapper for scheduling with market hour awareness.
    Can be called by GitHub Actions at 6:00 AM ET.
    """
    logger.info("=== Daily Pre-Market Run ===")
    success = run_daily_pipeline()
    
    if success:
        logger.info("Pipeline completed successfully. Dashboard will auto-update.")
    else:
        logger.error("Pipeline failed. Check logs for details.")
    
    return success


if __name__ == "__main__":
    run_daily_pipeline()
